### ISSUE TITLE
Wiki issue for generate_key

### ISSUE THREAD

**Issue by brandonsturgeon** [interactions-py/persistence#10]
This section of the Wiki tells users to import `generate_key` from the wrong place:
https://github.com/interactions-py/persistence/wiki#loading-the-extension

The line should read: 
> (This has reportedly not worked for some so you can also import the key generation function like so: `from interactions.ext.persistence.cipher import generate_key`)

**Comment by Dworv** [comment]
Actually, the name of the script has been changed to `keygen`. It should print a cipher token to stdout. I will adjust the wiki. Thanks

**Comment by brandonsturgeon** [comment]
The line I posted also appears to work, but I'd like to use whatever's best
