### ISSUE TITLE
Extensions inheriting from PersistenceExtension don't call their __init__ methods

### ISSUE THREAD

**Issue by brandonsturgeon** [interactions-py/persistence#12]
Unlike classes inheriting from `interactions.Extension`, `PersistenceExtension`-based extensions never seem to have their `__init__` methods called.

Example:
```py
from interactions.ext.persistence import PersistenceExtension, extension_persistent_component


class ExampleThing(PersistenceExtension):
    def __init__(self, client):
        self.client = client
        self.packages = {}

    @extension_persistent_component("receive_thing")
    async def receiver(self, ctx, package):
        # Errors because `self.packages` doesn't exist
        self.packages.append(package)
```

**Comment by Catalyst4222** [comment]
If you do `print(ExampleThing(client))`, what does it show?

**Comment by Toricane** [comment]
Do you have a setup function?
```py
def setup(client):
    ExampleThing(client)
```
Put it underneath and outside the class

**Comment by Toricane** [comment]
Also try `print(self)`

**Comment by Toricane** [comment]
Try this:
```py
from loguru import logger
from interactions.ext.persistence import PersistenceExtension


class ExampleThing(PersistenceExtension):
    def __new__(cls, client):
        logger.info("I have been created with __new__")
        self = super().__new__(cls, client)
        logger.info(str(self))

    def __init__(self, client):
        logger.info("I have been initialized with __init__")
        logger.info(str(self))


def setup(client):
    ExampleThing(client)
```

**Comment by Catalyst4222** [comment]
> Also try `print(self)` (as an alternative option to Catalyst4222's)

That's not an alternative 🙂

Brandon, if you do `print(ExampleThing(client))` without overriding `__new__`, what does it show?

**Comment by brandonsturgeon** [comment]
> > Also try `print(self)` (as an alternative option to Catalyst4222's)
> 
> That's not an alternative 🙂
> 
> Brandon, if you do `print(ExampleThing(client))` without overriding `__new__`, what does it show?

`print` doesn't show up in my logs - probably some log level thing.
Instead, I did `logger(str(ExampleThing(client)))`:

```
bot_1  | 2022-07-13 04:16:36.808 | INFO     | test_extension:setup:12 - None
```

**Comment by Dworv** [comment]
Can you try now? Install with `pip install --upgrade git+https://github.com/interactions-py/persistence` to try the patch. Let me know if anything continues to go wrong.

**Comment by brandonsturgeon** [comment]
Yep, it does appear to work! Thank you 😄
```
INFO     | test_extension:__init__:8 - I have been initialized with __init__
INFO     | test_extension:setup:12 - <test_extension.ExampleThing object at 0x7f34dc9bd780>
```
