### ISSUE TITLE
[REQUEST] stacking Decorator

### ISSUE THREAD

**Issue by Donbur4156** [interactions-py/persistence#13]
**Is your feature request related to a problem? Please describe.**

**Describe the your new feature**
Possibility to stack the Decorator: `@bot.persistent_component("tag")`
...and for modals as well.

**Describe alternatives you've considered**
atm you have to write a function for each decorator which point to one main function.

**Comment by Dworv** [comment]
@Donbur4156 
I'm not going to implement this for a while. If you really want it, definitely consider implementing it for yourself. Obviously, I will get to it eventually but if you wamt this feature soon and maybe a step closer to becoming an official ext dev, consider trying to implement this for yourself.

**Comment by Donbur4156** [comment]
Its makes the code cleaner. I'm going to try this by time.

**Comment by Dworv** [comment]
Marking this as a bug as well since this should work. You are making the decorators work as expected.

**Comment by Dworv** [comment]
#17
