### ISSUE TITLE
Logging: TypeError

### ISSUE THREAD

**Issue by Donbur4156** [interactions-py/persistence#6]
Little Error when starting the bot by registering modal/components.

TypeError: not all arguments converted during string formatting

```
  File "\.venv\lib\site-packages\interactions\ext\persistence\persistence.py", line 69, in inner
    logging.debug("Registered persistent modal:", tag)
Message: 'Registered persistent modal:'
Arguments: ('modal_name',)
```

In two lines I changed the string formatting to f-string as in core bib. PR is following. #7

**Comment by Dworv** [comment]
Oh I see what you mean. Good catch. Gl with the PR.

**Comment by Dworv** [comment]
#7
